config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  root :to => 'home#home'
  get '/subscriptions/list', to: 'subscriptions#list'
  get '/subscriptions/delete', to: 'subscriptions#delete'
  get '/subscriptions/add', to: 'subscriptions#add'
  get '/subscriptions/ratelist', to: 'subscriptions#ratelist'
  post '/subscriptions/delete', to: 'subscriptions#delete'
  post '/subscriptions/add', to: 'subscriptions#add'
  get '/feeds/list', to: 'feeds#list'
  get '/feeds/create', to: 'feeds#create'
  get '/feeds/save', to: 'feeds#save'
  post '/feeds/save', to: 'feeds#save'
  post '/feeds/search', to: 'feeds#search'
  get '/feeds/search_input', to: 'feeds#search_input'
  resources :relationships,       only: [:create, :destroy]

end

app/models/feed.rb
class Feed < ActiveRecord::Base
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :feed
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Follow relationship constraint
  has_many :active_relationships, class_name:  "Relationship",
                                foreign_key: "follower_id",
                                dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                foreign_key: "followed_id",
                                dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  ActionView::Base.field_error_proc = Proc.new { |html_tag, instance| "#{html_tag}".html_safe }
  def after_sign_in_path_for(resourse)
  	subscriptions_list_url
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
    before_action :authenticate_user!

    def list
        @url = params[:address]

        # Add one of read time in the database
        @feed=Feed.where("source=?",@url)
        if @feed[0].ReadNumber.nil?
            @feed[0].ReadNumber=1
            @feed[0].save
        else
            @feed[0].ReadNumber=@feed[0].ReadNumber+1
            @feed[0].save
        end

        @feed = Feedjira::Feed.fetch_and_parse @url
        # Not used in frontend
        @result=@feed.title

    end

    # Save the feed info
    def save
        @feed=params[:feed]
        @url=@feed[:source]

        @feed_temp= Feedjira::Feed.fetch_and_parse @url

        # Probe if the feed exist

        @veify=Feed.where("source=?", @url)


        if @verify.nil?
            @feed=Feed.new();
            @feed.name=@feed_temp.title
            ### Saved url is the url to retrieve rss info, different from the url in rss
            @feed.source=@url
            @feed.save
        end

        @feed=Feed.where("source=?", @url)
        @feed_id=@feed[0].id

        # Probe if the feed is in users scbscription list

        @subscription_probe=Subscription.where("feed_id=?",@feed_id)

        if @subscription_probe.empty?
            # Use empty here for where returns an array
            @subscription={}
            @subscription[:feed_id]=@feed_id
            redirect_to :controller=>'subscriptions', :action=>'add', :subscription=>@subscription
        end

        # If in list, back to index

        # redirect_to :controller=>'subscriptions', :action=>'index'

    end

    # Provide test save action form
    def create
        @feed=Feed.new()
    end

   def search_input
        @feed=Feed.new()
    end

    def search
        keyword=params[:feed][:source]
        counter=0
        @feed=Array.new()
        feedlist=Feed.all
        feedlist.each do |feedsource|
            entries_tmp=Feedjira::Feed.fetch_and_parse feedsource.source
            entries_tmp.entries.each do |article|
                if article.title.index(keyword)
                    @feed[counter]=article
                    counter+=1
                end
            end
        end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
    before_action :authenticate_user!

    def list
        @userid=current_user.id

        # Get subscription list
        @subscriptionslist=Subscription.where("user_id=?",@userid)

        # Set initializaion number
        @counter=-1
        @feedlist=Array.new

        # Add feed info to feedlist
        @subscriptionslist.each do |subscription|
            @counter+=1
            @feedlist[@counter]=Feed.where("id=?",subscription.feed_id)
        end
    end

    def add

        # Save feed in users subscription list

        @feed_id=params[:subscription]
        @feed_id=@feed_id[:feed_id]
        @user_id=current_user.id

        # Add to subscription

        @subscriptiontemp=Subscription.new()
        @subscriptiontemp.feed_id=@feed_id
        @subscriptiontemp.user_id=@user_id
        @subscriptiontemp.save

        redirect_to :action=>:list
    end

    def delete

        # Delete subscription from DB

        @userid=current_user.id
        @feedid=params[:subscription][:feed_id]
        @feed=Subscription.where("user_id=? and feed_id=?", @userid, @feedid)
        @subscription=Subscription.find_by(id: @feed[0].id)
        @subscription.destroy if !@subscription.nil?

        redirect_to :action=>:list
    end

    def ratelist
        # Order the result by ReadNumber
        @feeds=Feed.order("ReadNumber DESC")

        # Put the 10 most readed feed into the output list
        @feedlist=@feeds.take(10)

        # Count the number of output feeds
        @number=0
        (0..9).each do |counter|
            unless @feedlist[counter].nil?
                @number=@number+1
            end
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class='row'>
      <em class='red-text'>#{messages}</em>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/feeds/_list.html.erb
<br>
<div class="row">
	<div class="col s12 offset-m2 m8 offset-l3 l6">
		<ul class="tabs">
			<li class="tab">
				<a href="<%= @feed.url %>" style="font-size:1.5em">
					<%= @feed.title %>
				</a>
			</li>
		</ul>
	</div>
</div>
<% @feed.entries.each do |f| %>
<div class="row">
	<div class="col s12 offset-m2 m8 offset-l3 l6">
		<div class="card">
			<% if f.image %>
				<div class="card-image waves-effect waves-block waves-light">
					<img src="<%= f.image %>">
				</div>
			<%end%>
			<div class="card-content waves-effect waves-block waves-light">
				<span class="card-title black-text"><%= f.title %></span><br>
				<span class="card-title black-text" style="font-size:1em"><%= f.author %></span>
				<p><%= f.summary %></p>
			</div>
			<div class="card-action">
				<a href="<%= f.url %>" class="btn waves-effect waves-light orange accent-2 white-text">Read all</a>
				<button class="activator btn-floating waves-effect waves-light right orange"><i class="material-icons">share</i></button>
			</div>
			<div class="card-reveal">
				<span class="card-title orange-text text-darken-4">Share<i class="material-icons right">close</i></span>
				<%= social_share_button_tag(f.title, :url => f.url)%>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/feeds/_search.html.erb
<br>
<div class="row">
	<div class="col s12 offset-m2 m8 offset-l3 l6">
		<ul class="tabs">
			<li class="tab">
				<a  style="font-size:1.5em">
					search result
				</a>
			</li>
		</ul>
	</div>
</div>
<% @feed.each do |f| %>
<div class="row">
	<div class="col s12 offset-m2 m8 offset-l3 l6">
		<div class="card">
			<% if f.image %>
				<div class="card-image waves-effect waves-block waves-light">
					<img src="<%= f.image %>">
				</div>
			<%end%>
			<div class="card-content waves-effect waves-block waves-light">
				<span class="card-title black-text"><%= f.title %></span><br>
				<span class="card-title black-text" style="font-size:1em"><%= f.author %></span>
				<!--<p><%= f.summary %></p>-->
			</div>
			<div class="card-action">
				<a href="<%= f.url %>" class="btn waves-effect waves-light orange accent-2 white-text">Read all</a>
				<button class="activator btn-floating waves-effect waves-light right orange"><i class="material-icons">share</i></button>
			</div>
			<div class="card-reveal">
				<span class="card-title orange-text text-darken-4">Share<i class="material-icons right">close</i></span>
				<%= social_share_button_tag(f.title, :url => f.url)%>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/feeds/create.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<%= render "layouts/side" %>
<div class='row'>
	<div class="valign-wrapper">
		<div class="valign center" style="width: 100%;">
			<h2 class='cyan-text text-darken-3' style='text-align:center'></h2><br>
		</div>
	</div>
	<%= form_for @feed, :url => feeds_save_path, :html => {class: 'col s12 offset-m2 m8 offset-l3 l6'} do |f| %>
	<div class="card-panel z-depth-1">
		<div class='row col s12'>
			<div class="input-field">
				<i class="material-icons prefix">assessment</i>
				<%= f.label :source, "The url of feed:" %>
				<%= f.text_field :source %>
			</div>
		</div>
		<div class='row red-text'>
			<div class='col s12 center'>
			<%= button_tag(type: "submit", :class => "btn waves-effect waves-light") do %>
				Add Feed
				<i class="material-icons left">add</i>
			<% end %>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/feeds/list.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<%= render "layouts/side" %>
<%= render "list" %>

app/views/feeds/save.html.erb
<h3>The feed info has been saved.</h3>
<%= @subscription_probe.each do |f| %>
<% end %>

app/views/feeds/search.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<%= render "layouts/side" %>
<%= render "search" %>

app/views/feeds/search_input.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<%= render "layouts/side" %>
<div class='row'>
	<div class="valign-wrapper">
		<div class="valign center" style="width: 100%;">
			<h2 class='cyan-text text-darken-3' style='text-align:center'></h2><br>
		</div>
	</div>
	<%= form_for @feed, :url => feeds_search_path, :html => {class: 'col s12 offset-m2 m8 offset-l3 l6'} do |f| %>
	<div class="card-panel z-depth-1">
		<div class='row col s12'>
			<div class="input-field">
				<i class="material-icons prefix">assessment</i>
				<%= f.label :source, "Search Keyword:" %>
				<%= f.text_field :source %>
			</div>
		</div>
		<div class='row red-text'>
			<div class='col s12 center'>
			<%= button_tag(type: "submit", :class => "btn waves-effect waves-light") do %>
				search
				<i class="material-icons left">search</i>
			<% end %>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/home/home.html.erb
<div class="parallax-container">
	<div class="parallax"><%= image_tag "1.jpg" %></div>
</div>

<div class="section no-pad-bot" id="index-banner">
	<div class="container">
		<br><br>
		<h1 class="header center" style="color:#26a69a">Start Reading</h1>
		<div class="row center">
			<h5 class="header col s12 light black-text">A modern RSS reader based on Material Design</h5>
		</div>
		<div class="row center">
			<%= link_to 'Get Started', {:controller=>:"devise/sessions", :action=>:new}, :class=>"btn-large waves-effect waves-light teal lighten-1" %>
		</div>
		<br><br>
	</div>
</div>

<div class="parallax-container">
	<div class="parallax"><%= image_tag "2.jpg" %></div>
</div>

<div class="container">
	<div class="section no-pad-bot">
	<!-- Icon Section -->
		<div class="row">
			<div class="col s12 m4">
				<div class="icon-block">
					<h2 class="center" style="color:#26a69a"><i class="large material-icons">flash_on</i></h2>
					<h5 class="center black-text">Fast</h5>
					<p class="light black-text">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
				</div>
			</div>
			<div class="col s12 m4">
				<div class="icon-block">
					<h2 class="center" style="color:#26a69a"><i class="large material-icons">group</i></h2>
					<h5 class="center black-text">Share</h5>
					<p class="light black-text">Sharing with your friends, let good reading materials get seperated. When you are happy with some articles, let others share your happiness.</p>
				</div>
			</div>
			<div class="col s12 m4">
				<div class="icon-block">
					<h2 class="center" style="color:#26a69a"><i class="large material-icons">settings</i></h2>
					<h5 class="center black-text">Personalize</h5>
					<p class="light black-text">We have provided high-personalized reading service to help new users better reading. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
				</div>
			</div>
		</div>
	</div>
	<br>
</div>

<div class="parallax-container">
	<div class="parallax"><%= image_tag "3.jpg" %></div>
</div>

app/views/layouts/_side.html.erb
<div class="fixed-action-btn" style="bottom: 20%; right: 2%;">
	<a class="btn-floating btn-large teal lighten-1">
		<i class="mdi-navigation-menu"></i>
	</a>
	<ul>
		<li><%= link_to '<i class="material-icons">visibility</i>'.html_safe, {:controller=>:subscriptions, :action=>:ratelist}, :class=>"btn-floating red lighten-1" %></li>
		<li><%= link_to '<i class="material-icons">search</i>'.html_safe, {:controller=>:feeds, :action=>:search_input}, :class=>"btn-floating teal accent-3" %></li>
		<li><%= link_to '<i class="material-icons">list</i>'.html_safe, {:controller=>:subscriptions, :action=>:list}, :class=>"btn-floating yellow darken-3" %></li>
		<li><%= link_to '<i class="material-icons">add</i>'.html_safe, {:controller=>:feeds, :action=>:create}, :class=>"btn-floating light-blue accent-2" %></li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RSS Reader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body class='amber lighten-5' style="display: flex; min-height: 100vh; flex-direction: column;">
	<header>
	<nav>
		<div class='nav-wrapper'>
			<a href="/" class='brand-logo center'>RSS Reader</a>
			<ul id='nav-mobile' class='right hide-on-med-and-down'>
				<% if current_user %>
				<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
				<li><%= link_to('Change Password', edit_registration_path(:user)) %></li>
				<% else %>
				<li><%= link_to('Sign Up', new_registration_path(:user)) %></li>
				<li><%= link_to('Login', new_session_path(:user)) %></li>
				<% end %>
			</ul>
		</div>
	</nav>
	</header>
	<main style='flex: 1 0 auto;'>
		<%= yield %>
	</main>
	<footer class="page-footer" style="margin:0">
		<div class="container">
			<div class="row">
				<div class="col l6 s12">
					<h5 class="white-text">Group 5</h5>
					<h6 class="white-text">Chang Su</h6>
					<h6 class="white-text">Jiahao Ke</h6>
					<h6 class="white-text">Min Yang</h6>
					<h6 class="white-text">Xiaoyu Wang</h6>
					<h6 class="white-text">Zhenqi Zhu</h6>
				</div>
				<div class="col l4 offset-l2 s12">
					<h5><a href="https://csil-git1.cs.surrey.sfu.ca/xwa129/rssReader" class="white-text">Gitlab</a></h5>
				</div>
			</div>
		</div>
		<div class="footer-copyright">
			<div class="container">
				© 2015 Copyright Text
			</div>
		</div>
	</footer>
</body>
</html>

app/views/subscriptions/_list.html.erb
<div class="row">
	<table class="card-panel z-depth-1 hoverable col s12 offset-m2 m8 offset-l3 l6">
			<thead>
			</thead>
			<tbody>
				<% (0..@counter).each do |counter| %>
				<tr>
					<% @feedlist[counter].each do |feed| %>
						<% feed.id %>
						<td style="text-align:center; font-size:1.5em;">
							<%= link_to feed.name, {:controller=>:feeds, :action=>:list, :address=>feed.source}, :class=>"black-text" %>
						</td>
						<td style="text-align:center">
							<%= link_to '<i class="material-icons">delete</i>'.html_safe,
								subscriptions_delete_path(:subscription=>{:feed_id=>feed.id}),
								:class=>"btn-floating red",
								data: { confirm: 'Are you sure?' } %>
						</td>
						<% feed.source %>
					<% end %>
				</tr>
				<% end %>
			</tbody>
	</table>
</div>

app/views/subscriptions/_ratelist.html.erb
<div class="row"></div>
<div class="row">
    <div class="col s12 offset-m2 m8 offset-l3 l6">
        <ul class="tabs">
            <li class="tab">
                <a style="font-size:1.5em">
                    Rating List by Click Rate
                </a>
            </li>
        </ul>
    </div>
</div>
<div class="row">
    <table class="card-panel z-depth-1 hoverable col s12 offset-m2 m8 offset-l3 l6">
        <thead>
        </thead>
        <tbody>
            <% (0..@number-1).each do |counter| %>
            <tr>
                <% @feedlist[counter].id %>
                <td style="text-align:center; font-size:1.5em;">
                    <%= link_to @feedlist[counter].name, {:controller=>:feeds, :action=>:list, :address=>@feedlist[counter].source}, :class=>"black-text" %>
                </td>
                <td style="text-align:center">
                    <%= link_to '<i class="material-icons">add</i>'.html_safe,
                    subscriptions_add_path(:subscription=>{:feed_id=>@feedlist[counter].id}),
                    :class=>"btn-floating red",
                    data: { confirm: 'Are you sure?' } %>
                </td>
                <% @feedlist[counter].source %>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/subscriptions/list.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<%= render "layouts/side" %>
<%= render "list" %>

app/views/subscriptions/ratelist.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<%= render "layouts/side" %>
<%= render "ratelist" %>